In [62]:
import pandas as pd
data=pd.read_csv('/content/Bike_prices_after_outlier_removal.csv')
display(data)

,Unnamed: 0,Brand,Model,Selling_Price,Year,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
0,0,TVS,TVS XL 100,30000,2017,Individual,1st owner,8000,30490.0
1,1,Bajaj,Bajaj ct 100,18000,2017,Individual,1st owner,35000,32000.0
2,2,Yo,Yo Style,20000,2011,Individual,1st owner,10000,37675.0
3,3,Bajaj,Bajaj Discover 100,25000,2010,Individual,1st owner,43000,42859.0
4,4,Bajaj,Bajaj Discover 100,24999,2012,Individual,2nd owner,35000,42859.0
...,...,...,...,...,...,...,...,...,...
827,1056,Royal,Royal Enfield Electra 5 S,90000,2012,Individual,1st owner,40000,50267.0
828,1057,Hero,Hero Honda Hunk,20000,2010,Individual,1st owner,17000,50267.0
829,1058,Bajaj,Bajaj Pulsar 220 DTS-i,60000,2014,Individual,1st owner,16000,50267.0
830,1059,Hero,Hero Honda CBZ extreme,40000,2009,Individual,1st owner,50000,50267.0
831,1060,Hero,Hero Honda CBZ extreme,35000,2012,Individual,1st owner,60000,50267.0

In [63]:
value_count=['Brand','Model','Year','Seller_Type','Owner']

In [64]:
for v in value_count:
  dat=data.value_counts(v)
  display(dat)

Brand
Bajaj       242
Hero        204
Honda       183
Yamaha       72
TVS          61
Royal        29
Suzuki       27
Vespa         4
Mahindra      4
Aprilia       2
Activa        2
KTM           1
Yo            1
Name: count, dtype: int64

Model
Bajaj Pulsar 150              39
Bajaj Pulsar 180              20
Honda CB Hornet 160R          19
Honda Activa [2000-2015]      18
Bajaj Discover 125            16
                              ..
Yamaha SZ [2013-2014]          1
Yamaha SZ-S                    1
Yamaha Saluto RX               1
Yamaha YZF R15 [2011-2018]     1
Yo Style                       1
Name: count, Length: 213, dtype: int64

Year
2017    92
2016    90
2018    90
2015    84
2014    81
2013    64
2012    62
2011    55
2010    53
2019    52
2008    24
2009    23
2007    22
2006    19
2005    14
2002     3
2004     3
2003     1
Name: count, dtype: int64

Seller_Type
Individual    829
Dealer          3
Name: count, dtype: int64

Owner
1st owner    727
2nd owner     97
3rd owner      8
Name: count, dtype: int64

In [65]:
order=data['Year'].unique()
order.sort()
print(order)

[2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015
 2016 2017 2018 2019]

In [66]:
from sklearn.preprocessing import OrdinalEncoder
ord=OrdinalEncoder(categories=[order])
data['Year']=ord.fit_transform(data[['Year']])

display(data)

,Unnamed: 0,Brand,Model,Selling_Price,Year,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
0,0,TVS,TVS XL 100,30000,15.0,Individual,1st owner,8000,30490.0
1,1,Bajaj,Bajaj ct 100,18000,15.0,Individual,1st owner,35000,32000.0
2,2,Yo,Yo Style,20000,9.0,Individual,1st owner,10000,37675.0
3,3,Bajaj,Bajaj Discover 100,25000,8.0,Individual,1st owner,43000,42859.0
4,4,Bajaj,Bajaj Discover 100,24999,10.0,Individual,2nd owner,35000,42859.0
...,...,...,...,...,...,...,...,...,...
827,1056,Royal,Royal Enfield Electra 5 S,90000,10.0,Individual,1st owner,40000,50267.0
828,1057,Hero,Hero Honda Hunk,20000,8.0,Individual,1st owner,17000,50267.0
829,1058,Bajaj,Bajaj Pulsar 220 DTS-i,60000,12.0,Individual,1st owner,16000,50267.0
830,1059,Hero,Hero Honda CBZ extreme,40000,7.0,Individual,1st owner,50000,50267.0
831,1060,Hero,Hero Honda CBZ extreme,35000,10.0,Individual,1st owner,60000,50267.0

In [67]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Brand'] = le.fit_transform(data['Brand'])
data['Model'] = le.fit_transform(data['Model'])
display(data)

,Unnamed: 0,Brand,Model,Selling_Price,Year,Seller_Type,Owner,KM_Driven,Ex_Showroom_Price
0,0,9,183,30000,15.0,Individual,1st owner,8000,30490.0
1,1,2,3,18000,15.0,Individual,1st owner,35000,32000.0
2,2,12,212,20000,9.0,Individual,1st owner,10000,37675.0
3,3,2,16,25000,8.0,Individual,1st owner,43000,42859.0
4,4,2,16,24999,10.0,Individual,2nd owner,35000,42859.0
...,...,...,...,...,...,...,...,...,...
827,1056,7,145,90000,10.0,Individual,1st owner,40000,50267.0
828,1057,3,67,20000,8.0,Individual,1st owner,17000,50267.0
829,1058,2,36,60000,12.0,Individual,1st owner,16000,50267.0
830,1059,3,64,40000,7.0,Individual,1st owner,50000,50267.0
831,1060,3,64,35000,10.0,Individual,1st owner,60000,50267.0

In [68]:
lis_on=['Seller_Type','Owner']

In [69]:
from sklearn.preprocessing import OneHotEncoder

for o in lis_on:
    on=OneHotEncoder(sparse_output=False,drop='first')

    st=on.fit_transform(data[[o]])

    st=pd.DataFrame(st,columns=on.get_feature_names_out([o]))

    data=pd.concat((data,st),axis=1)
    data=data.drop(columns=o)
data

,Unnamed: 0,Brand,Model,Selling_Price,Year,KM_Driven,Ex_Showroom_Price,Seller_Type_Individual,Owner_2nd owner,Owner_3rd owner
0,0,9,183,30000,15.0,8000,30490.0,1.0,0.0,0.0
1,1,2,3,18000,15.0,35000,32000.0,1.0,0.0,0.0
2,2,12,212,20000,9.0,10000,37675.0,1.0,0.0,0.0
3,3,2,16,25000,8.0,43000,42859.0,1.0,0.0,0.0
4,4,2,16,24999,10.0,35000,42859.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
827,1056,7,145,90000,10.0,40000,50267.0,1.0,0.0,0.0
828,1057,3,67,20000,8.0,17000,50267.0,1.0,0.0,0.0
829,1058,2,36,60000,12.0,16000,50267.0,1.0,0.0,0.0
830,1059,3,64,40000,7.0,50000,50267.0,1.0,0.0,0.0
831,1060,3,64,35000,10.0,60000,50267.0,1.0,0.0,0.0

In [74]:
data.to_csv('encoded_bike_prices.csv',index=False)